Traceback (most recent call last):
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\kmaull\AppData\Local\anaconda3\envs\jbook\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import folium
map_eq = folium.Map(location=[37.733795, -122.446747], zoom_start=2)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mfolium[39;00m
[0;32m      2[0m map_eq [38;5;241m=[39m folium[38;5;241m.[39mMap(location[38;5;241m=[39m[[38;5;241m37.733795[39m, [38;5;241m-[39m[38;5;241m122.446747[39m], zoom_start[38;5;241m=[39m[38;5;241m2[39m)

[1;31mModuleNotFoundError[0m: No module named 'folium'

